apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edukan-eureka
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: adena.local
    http:
      paths: 
      - path: /eurekaserviceregister
        pathType: Prefix
        backend:
          service:
            name: edukan-eureka
            port:
              number: 8761